id: A8E9BC08F
title: The Noble Mārīcī Dhāraṇī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:39:04.757104
  last_modified_at: 2022-03-01 04:39:04.757110
