id: A8E9BC08F
title: A S훮dhana of M훮r카c카
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:39:04.750574
  last_modified_at: 2022-03-01 04:39:04.750580
