id: A8E9BC08F
title: In Praise of the Goddess Mārīcī (Özerchenma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:39:04.753161
  last_modified_at: 2022-03-01 04:39:04.753165
